version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys: 
          fingerprints:
            - "5a:29:79:47:86:86:00:da:35:05:2f:c2:2f:2b:33:1e"
      - checkout
      - run: 
         name: Clone Repo abap-ci-pipeline
         command: |
          git clone -b 'master' git@github.com:mepmarcelo/abap-ci-pipeline.git
          cd abap-ci-pipeline
          npm install
          npm run abapUnit 


