version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys: 
          fingerprints:
            - "a6:bb:25:31:95:59:15:5e:03:1f:7d:b3:30:27:ac:e2"
      - checkout
      - run: 
         name: Clone Repo abap-ci-pipeline-new
         command: |
          git clone -b 'master' git@github.com:mepmarcelo/abap-ci-pipeline-new.git
          cd abap-ci-pipeline-new
          npm install
          npm run abapUnit
        - store_test_results:
          path: abap-unit/reports


